Themes/underscore
KajiwaraMidori/enjoy_vegan_hp pull request #22
Opened 2018-02-27 14:00 UTC by TsubasaK111

@KajiwaraMidori review me!

2018-02-27 17:09 UTC, KajiwaraMidori reviewed
oriaとsandboxの作業内容はdevにマージした方がいい？
もし不要なら、マージ対象から外せるかな？

対象commitは以下4つ

f442468
d0fb7af
4212ced
b7a3f70

2018-02-28 01:06 UTC, TsubasaK111 commented
確かに、`dev` が汚れるな

2018-02-28 16:03 UTC, KajiwaraMidori requested changes
devにmergeしたい変更だけにしよう〜！（oriaとsandboxは不要）

2018-03-10 08:01 UTC, KajiwaraMidori approved these changes

2018-03-10 08:01 UTC, merged