feat: add svg files, add h1 element (for SEO)
KajiwaraMidori/enjoy_vegan_hp pull request #48
Opened 2018-05-03 14:00 UTC by TsubasaK111

2018-05-03 15:58 UTC, KajiwaraMidori commented
1）新しく追加されてるhashtag_l.pngってなに？（使用箇所なし。不要ファイルでは？）
2）不要になったpngファイルを削除してほしい
3）site descriptionもh1にしてSEO対策したい
4）evg_logoを小さくして日本地図寄り（右寄り）にしたい（沖縄より左にはみ出さない）
5）click! Search by hashtagを小さくして日本地図寄り（左寄り）にしたい（北海道よりはみ出さない）

2018-05-03 15:59 UTC, KajiwaraMidori requested changes
修正依頼コメント残しました！

2018-05-04 14:19 UTC, TsubasaK111 commented
1) これは間違い、消す。
2）ガッテン承知。
3）site descriptionはすでに73行目から始まっているh1の配下。
4）evj_logoを小さくして日本地図寄り（右寄り）にしたい（沖縄より左にはみ出さない）
      これはモックアップを確認したら沖縄よりはみ出ていたのでこうした。個人的にはサイズも位置もこっちのほうがバランスが良いと感じるのだが、今一度確認して欲しい。
5）ガッテン承知
6）click! を小さくして、Search by hashtagと共に日本地図寄り（左寄り）にしたい（北海道よりはみ出さない）
     4. に同じ、バランス悪い。clickは小さくする。

2018-05-04 14:21 UTC, TsubasaK111 commented
![screen shot 2018-05-04 at 23 18 22](https://user-images.githubusercontent.com/14030265/39633020-c0099b74-4ff1-11e8-8306-d21c950871ab.png)
4)と6)はやって見たけど、やはりなんかやたら窮屈に感じる。
無駄な余白が左右に発生して、重心が画面の中心ではない感じになる。
https://github.com/KajiwaraMidori/enjoy_vegan_hp/tree/themes/header-svg_mk2

2018-05-04 14:43 UTC, TsubasaK111 commented
1), 2), 5) 修正。 review me agan!

2018-05-04 16:35 UTC, KajiwaraMidori commented
1）修正、確認します！
2）修正、確認します！
3）承知しました！
4）イメージ図を投げまする
5）修正、確認します！
6）4に同じ。
<img width="676" alt="2018-05-05 1 31 32" src="https://user-images.githubusercontent.com/32909531/39640022-a61569d8-5004-11e8-9d1b-8c12e28ffbfa.png">

2018-11-27 17:35 UTC, closed without merging